openapi: 3.0.3
info:
  title: Simple Food API - Common Schemas
  version: 0.1.0-draft
  description: Common and base entities reused across Simple Food API specs
tags:
  - name: Products
    description: Product resources
  - name: Dishes
    description: Dish resources
servers: []
paths:
  /products:
    $ref: 'spec-simple-food-api-products.yaml#/paths/~1products'
  /products/{id}:
    $ref: 'spec-simple-food-api-products.yaml#/paths/~1products~1{id}'
  /products/search:
    $ref: 'spec-simple-food-api-products.yaml#/paths/~1products~1search'
  /dishes:
    $ref: 'spec-simple-food-api-dishes.yaml#/paths/~1dishes'
  /dishes/{id}:
    $ref: 'spec-simple-food-api-dishes.yaml#/paths/~1dishes~1{id}'
  /dishes/search:
    $ref: 'spec-simple-food-api-dishes.yaml#/paths/~1dishes~1search'
components:
  schemas:
    BaseRequest:
      type: object
      description: Base request envelope for API operations
      properties:
        requestId:
          type: string
          format: uuid
        timestamp:
          type: string
          format: date-time
        author:
          $ref: '#/components/schemas/Author'
      required: [requestId, timestamp]

    BaseResponse:
      type: object
      description: Base response envelope for API operations
      properties:
        requestId:
          type: string
          format: uuid
        success:
          type: boolean
        error:
          $ref: '#/components/schemas/Error'
      required: [requestId, success]

    Measure:
      type: string
      description: Measurement unit for weights/amounts
      enum: [g, kg, ml, l, pcs]

    Weight:
      type: object
      description: Quantity with measurement unit
      properties:
        value:
          type: number
          format: float
        measure:
          $ref: '#/components/schemas/Measure'
      required: [value, measure]

    Error:
      type: object
      description: Standard error object
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: object
          additionalProperties: true
      required: [code, message]

    Author:
      type: object
      description: Author of the entity or request initiator
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        email:
          type: string
          format: email
      required: [id]

    Id:
      type: string
      format: uuid

    Product:
      $ref: './spec-simple-food-api-products.yaml#/components/schemas/Product'

    Dish:
      $ref: './spec-simple-food-api-dishes.yaml#/components/schemas/Dish'


