package com.khan366kos.mapper.toContext

import com.khan366kos.common.model.common.BeId
import com.khan366kos.common.model.common.BeLocale
import com.khan366kos.common.model.measure.BeMeasure
import com.khan366kos.common.model.measure.BeMeasureCode
import com.khan366kos.common.model.measure.BeMeasureName
import com.khan366kos.common.model.measure.BeMeasureShortName
import com.khan366kos.common.model.measure.BeMeasureTranslation
import com.khan366kos.common.model.measure.BeMeasureWithTranslations
import com.khan366kos.transport.model.MeasureDetail
import com.khan366kos.transport.model.MeasureDetailCreateRequest
import com.khan366kos.transport.model.MeasureTranslation
import java.time.Instant

/**
 * Convert MeasureDetailCreateRequest to context model (for POST - ID will be generated by repository)
 */
fun MeasureDetailCreateRequest.toContext(): BeMeasureWithTranslations = BeMeasureWithTranslations(
    measure = BeMeasure(
        code = BeMeasureCode(code),
        createdAt = Instant.now()
    ),
    translations = translations.map { it.toContext(BeId.NONE) }
)

/**
 * Convert MeasureDetail to context model (for PUT - preserves existing ID)
 */
fun MeasureDetail.toContext(): BeMeasureWithTranslations = BeMeasureWithTranslations(
    measure = BeMeasure(
        id = BeId(id.toString()),
        code = BeMeasureCode(code),
        createdAt = Instant.now()
    ),
    translations = translations.map { it.toContext(BeId(id.toString())) }
)

fun MeasureTranslation.toContext(measureId: BeId): BeMeasureTranslation = BeMeasureTranslation(
    id = measureId,
    locale = BeLocale(locale),
    name = BeMeasureName(measureName),
    shortName = BeMeasureShortName(measureShortName)
)
